# Generated by Django 3.1.1 on 2020-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sell',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
