# Generated by Django 3.1.1 on 2021-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200929_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_packed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_placed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_shipped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_shipping',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
