# Generated by Django 3.1.1 on 2021-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210511_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='design_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='custom',
            name='tshirt_size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
