# Generated by Django 3.1.1 on 2021-05-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_custom_quentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_order', to='store.order'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
